---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: manoj
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/manojkrgupta/test_fluxcd
  secretRef:
    name: flux-github-auth

