# clusters/dev/flux-system/gotk-sync.yaml

apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/manojkrgupta/test_fluxcd
  ref:
    branch: main
  ignore: |
    /clusters/dev/flux-system/**
  secretRef:
    name: flux-github-auth  

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
