---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manoj
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./clusters/dev/apps/
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: manoj
  targetNamespace: default
  timeout: 3m0s
  wait: true
