version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo Build started on `date`
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t mycodebuildtest .
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
